config/routes.rb
Rails.application.routes.draw do
  get "home/index"
  get "my_post", to: "posts#my_post"
  # resource :comments, only: [ :create, :destroy ]
  # resource :reactions, only: [ :create, :destroy ]

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  resources :posts do
    resources :comments
    resources :reactions, only: [ :create, :destroy ]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post
  before_action :set_comment, only: [:edit, :update, :destroy]

  def create
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user || current_user.admin?

    if @comment.save
      redirect_to @post, notice: "Comment was successfully created."
    else
      redirect_to @post, alert: "Failed to create comment."
    end
  end

  def edit;end

  def update
    @comment = Comment.find(params[:id])
    unless current_user.admin? || @comment.user == current_user
      redirect_to @comment.post, alert: "You are not authorized to edit this comment." and return
    end

    if @comment.update(comment_params)
      redirect_to @comment.post, notice: "Comment was successfully updated."
    else
      redirect_to @comment.post, alert: "Failed to update comment."
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    unless current_user.admin? || @comment.user == current_user
      redirect_to @comment.post, alert: "You are not authorized to delete this comment." and return
    end

    @comment.destroy
    redirect_to @comment.post, notice: "Comment was successfully deleted."
  end

  private

  def set_post
    @post = Post.friendly.find(params[:post_id])
  end

  def set_comment
    @comment = @post.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_edit_form.html.erb
<div class="mt-8">
    <h2 class="text-xl md:text-2xl font-bold">Comments</h2>
    <!-- Comment Form -->
    <% if user_signed_in? %>
    <div class="mt-2">
        <%= form_with model: [@post, comment], class: "flex flex-col gap-2" do |f| %>
        <%= f.text_area :body,
            placeholder: "Add a comment...",
            class: "w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none transition duration-200 text-sm" %>

        <%= f.submit "Update Comment",
            class: "btn btn-success btn-sm self-end" %>
        <% end %>
    </div>
    <% end %>
</div>

app/views/comments/_form.html.erb
<div class="mt-8">
    <h2 class="text-xl md:text-sm pl-2 font-bold">Comments</h2>
    <!-- Comment List -->
    <div class="space-y-4">
        <% @post.comments.each do |comment| %>
        <div class="shadow-md rounded-none p-3 transition duration-200">
            <p class="text-xs  mb-1">
                <strong><%= comment.user.username %></strong>
            </p>
            <p class="text-sm"><%= comment.body %></p>
            <div class="flex flex-row flex-row-reverse">
                <% if comment.user == current_user %>
                <%= link_to "Delete", 
                post_comment_path(@post, comment),
                data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this comment?" },
                class: "link link-hover link-error text-xs"%>
                <%= link_to "Edit", edit_post_comment_path(@post, comment), 
                class: "link link-hover link-info text-xs pr-2" %>
                <% end %>
            </div>
        </div>
        <% end %>
    </div>

    <!-- Comment Form -->
    <% if user_signed_in? %>
    <div class="mt-2">
        <%= form_with model: [@post, Comment.new], class: "flex flex-col gap-2" do |f| %>
        <%= f.text_area :body,
            placeholder: "Add a comment...",
            class: "w-full px-4 py-2 border border-gray-500 rounded-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none transition duration-200" %>

        <%= f.button type: "submit", class: "btn btn-success btn-sm self-end" do %>
        <%= icon "paper-airplane", library: "heroicons", class: "size-4 inline" %>
        Post comment
        <% end %>
        <% end %>
    </div>
    <% end %>
</div>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<div class="w-full max-w-2xl mx-auto mt-4 p-8 md:p-12 shadow-xl rounded-xl">
    <%= render "comments/edit_form", comment: @comment %>
</div>