config/routes.rb
Rails.application.routes.draw do
  get "home/index"
  get "my_post", to: "posts#my_post"
  # resource :comments, only: [ :create, :destroy ]
  # resource :reactions, only: [ :create, :destroy ]

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  resources :posts do
    resources :comments
    resources :reactions, only: [ :create, :destroy ]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
end

app/views/shared/_navigation.html.erb
<div class="w-full flex flex-col bg-base-100/70 border-b border-base-content/10 backdrop-blur-md backdrop-saturate-150 md:flex-row md:justify-between md:items-center shadow-sm p-5 px-16 z-10 top-0 left-0 sticky">
    <div class="flex items-center space-x-6 mb-4 md:mb-0">
        <%= link_to "Home", root_path, class: "link link-hover hover:text-amber-700 transition text-sm font-semibold" %>
        <%= link_to "Blogs", posts_path, class: "link link-hover hover:text-amber-700 transition text-sm font-semibold" %>

        <% if admin? %>
        <%= link_to "My blogs", my_post_path, class: "link link-hover hover:text-amber-700 transition text-sm font-semibold" %>
        <% end %>
    </div>
    <div class="flex items-center space-x-4">
        <% if user_signed_in? || admin? %>
        <div class="dropdown dropdown-center">
            <div tabindex="0" role="button" class="btn btn-ghost m-1 btn-sm">
                <%= icon "user-circle", library: "heroicons", class: "size-5 inline mr-1" %>
                Profile
            </div>
            <ul tabindex="-1" class="dropdown-content menu bg-base-100 rounded-box z-1 w-48 p-2 shadow-sm">
                <li>
                    <div>
                        <%= icon "cog-6-tooth", library: "heroicons", class: "size-4 inline mr-1" %>
                        <%= link_to "User settings", edit_user_registration_path %>
                    </div>
                </li>
                <li class="border-t border-gray-200 mt-2 pt-2">
                    <div>
                        <%= icon "arrow-left-start-on-rectangle", library: "heroicons", class: "size-4 inline text-red-500 mr-1" %>
                        <%= link_to "Log out", 
                        destroy_user_session_path, 
                        data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to log out?" }, 
                        class: "text-red-500 hover:text-red-700" %>
                    </div>
                </li>
            </ul>
        </div>
        <%= render "shared/theme_toggler" %>
        <% else %>
        <%= link_to "Sign up", 
            new_user_registration_path, 
            class: "btn btn-ghost btn-sm" %>
        <%= link_to "Sign in", 
            new_user_session_path, 
            class: "btn btn-primary btn-outline btn-sm" %>
        <% end %>
        <% if !user_signed_in? %>
        <%= render "shared/theme_toggler" %>
        <% end %>
    </div>
</div>

app/views/shared/_theme_toggler.html.erb
<div class="dropdown dropdown-end" data-controller="theme-persist" data-theme-persist-key-value="theme">
    <div tabindex="0" role="button" class="btn btn-ghost btn-sm">
        <%= icon "sun", library: "heroicons", class: "size-5 inline mr-1" %>
        Theme
    </div>
    <div tabindex="0" class="dropdown-content z-[999] mt-2 p-2 shadow bg-base-100 rounded-box w-64">
        <ul class="menu menu-sm max-h-72 overflow-auto">
            <% themes = %w[light dark cupcake bumblebee emerald corporate synthwave retro cyberpunk valentine halloween garden forest aqua lofi pastel fantasy wireframe black luxury dracula cmyk autumn business acid lemonade night coffee winter] %>
            <% themes.each do |t| %>
            <li>
                <label class="label cursor-pointer justify-between">
                    <span class="capitalize"><%= t %></span>
                    <input type="radio" name="theme-dropdown" class="theme-controller radio" value="<%= t %>" data-action="click->theme-persist#save" />
                </label>
            </li>
            <% end %>
        </ul>
    </div>
</div>

app/views/shared/_toaster.html.erb
<% if defined?(resource) && resource&.errors&.any? %>
<% flash.now[:alert] = resource.errors.full_messages.to_sentence %>
<% end %>
<% flash.each do |type, message| %>
<% bg_color = type == "notice" ? "bg-green-500" : "bg-red-500" %>

<div data-controller="toast" class="fixed top-5 right-5 z-50 <%= bg_color %> text-white px-6 py-3 rounded-lg shadow-lg flex items-center space-x-3 animate-slide-in">
    <span>
        <%= message %>
    </span>
    <button data-action="click->toast#close" class="text-white font-bold cursor-pointer">
        &times;
    </button>
</div>
<% end %>