config/routes.rb
Rails.application.routes.draw do
  get "home/index"
  get "my_post", to: "posts#my_post"
  # resource :comments, only: [ :create, :destroy ]
  # resource :reactions, only: [ :create, :destroy ]

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  resources :posts do
    resources :comments
    resources :reactions, only: [ :create, :destroy ]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% if !user_signed_in? %>
<div class="text-center py-12">
    <h1 class="text-4xl font-bold mb-4">Welcome to My Personal Blog</h1>
    <p class="text-lg mb-8">Sign in to start reading and writing blogs.</p>
    <%= link_to "Sign In" , new_user_session_path, class: "btn btn-primary" %>
</div>
<% else %>
<div class="text-center py-12">
    <h1 class="text-4xl font-bold mb-4">Welcome Back, <%= current_user.username %>!</h1>
    <p class="text-lg mb-8">Continue exploring the blog posts.</p>
    <%= link_to posts_path, class: "btn btn-primary items-center gap-2" do %>
    <%= icon "cursor-arrow-rays", library: "heroicons", class: "size-6 inline" %>
    View All Posts
    <% end %>
    <p class="text-sm mt-4">
        <% if admin? %>
        You can also <%= link_to "create a new post", new_post_path, class: "btn btn-sm" %>
        <% end %>
    </p>
</div>
<% end %>