config/routes.rb
Rails.application.routes.draw do
  get "home/index"
  get "my_post", to: "posts#my_post"
  # resource :comments, only: [ :create, :destroy ]
  # resource :reactions, only: [ :create, :destroy ]

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  resources :posts do
    resources :comments
    resources :reactions, only: [ :create, :destroy ]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true

  has_many :comments, dependent: :destroy
  has_many :reactions, dependent: :destroy
  has_one_attached :image
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[ index show ]
  before_action :require_admin!, except: %i[ index show ]
  before_action :set_post, only: %i[ show edit update destroy ]

  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def show;end

  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to @post, notice: "Blog post saved successfully.", status: :see_other
    else
      flash.now[:alert] = @post.errors.full_messages.to_sentence
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize_owner!
  end

  def update
    authorize_owner!
    if @post.update(post_params)
      redirect_to @post, notice: "Blog post updated successfully.", status: :see_other
    else
      flash.now[:alert] = @post.errors.full_messages.to_sentence
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize_owner!
    @post.destroy
    redirect_to posts_path, notice: "Post was successfully deleted.", status: :see_other
  end

  def my_post
    @posts = current_user.posts
  end

  private

  def set_post
    @post = Post.friendly.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to posts_path, alert: "Post not found."
  end

  def post_params
    # params.expect(post: [ :title, :body ]) # this is a more concise way to write the strong parameters, but it is not yet widely supported in all versions of Rails
    params.require(:post).permit(:title, :body, :user_id, :image) # currently the best practice
  end

  def authorize_owner!
    return if @post.user == current_user

    redirect_to @post, alert: "You are not authorized to perform this action."
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with model: post do |f| %>
<div class="mb-4">
    <%= f.label :title, class: "block text-sm font-medium mb-1 flex items-center gap-1" do %>
    <%= icon "bookmark", library: "heroicons", variant: "solid", class: "size-4 inline" %>
    Title
    <% end %>
    <%= f.text_field :title, placeholder: "Post title", class: "w-full px-4 py-2 border border-gray-400 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none transition" %>
</div>

<div class="mb-4">
    <%= f.label :body, class: "block text-sm font-medium mb-1 flex items-center gap-1" do %>
    <%= icon "chat-bubble-oval-left-ellipsis", library: "heroicons", variant: "solid", class: "size-4 inline" %>
    Body
    <% end %>
    <%= f.text_area :body, placeholder: "Write your post here...", class: "w-full h-50 px-4 py-2 border rounded-lg border-gray-400 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none transition" %>
</div>
<div class="mb-4">
    <%= f.label :image, class: "block text-sm font-medium mb-1 flex items-center gap-1" do %>
    <%= icon "photo", library: "heroicons", variant: "solid", class: "size-4 inline" %>
    Image
    <% end %>
    <%= f.file_field :image, class: "w-full px-4 py-2 border border-gray-400 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none transition" %>
</div>
<div class="flex gap-3 mt-4">
    <%= f.button type: "submit", class: "btn btn-success btn-sm w-[20%]" do %>
    <%= icon "paper-airplane", library: "heroicons", class: "size-4 inline" %>
    Submit
    <% end %>

    <%= link_to posts_path, class: "btn btn-neutral btn-sm" do %>
    <%= icon "arrow-left", library: "heroicons", class: "size-4 inline" %>
    Back to posts
    <% end %>
</div>
<% end %>

app/views/posts/_post.html.erb
<div class="card bg-base-100 w-full shadow-xl rounded-xl">
    <figure>
        <% if post.image.attached? %>
        <%= image_tag post.image, 
        class: "w-full h-50 rounded-lg mb-4 object-cover" %>
        <% end %>
    </figure>
    <div class="card-body">
        <h2 class="card-title text-center justify-center text-xl">
            <%= link_to post.title.capitalize, post_path(post), 
            class: "relative inline-block after:absolute after:left-0 after:bottom-0 after:w-0 after:h-[2px] after:bg-black after:transition-all after:duration-500 hover:after:w-full" %>
        </h2>
        <p class="text-center text-xs italic mb-2">
            <%= post.created_at.strftime("%B %d, %Y") %>
        </p>
        <div class="text-xs italic">
            <p class="text-base mb-4">
                <%= truncate(post.body, length: 150) %>
            </p>
        </div>
        <div class="badge badge-outline rounded-xl text-xs">
            ❤️ <%= post.reactions.count %>
            <%= "reaction".pluralize(post.reactions.count) %>
        </div>
    </div>
    <div class="card-actions justify-end mb-4 px-6">
        <%= link_to post_path(post), class: "btn btn-outline btn-sm hover:bg-neutral hover:text-white transition-colors duration-300" do %>
        <%= icon "cursor-arrow-rays", library: "heroicons", class: "size-4 inline" %>
        Read more
        <% end %>
        <% if admin? %>
        <%= link_to edit_post_path(post), class: "btn btn-info btn-outline btn-sm hover:bg-info hover:text-white transition-colors duration-300 w-[25%]" do %>
        <%= icon "pencil-square", library: "heroicons", class: "size-4 inline" %>
        Edit
        <% end %>
        <%= link_to post_path(post),
            data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-error btn-outline btn-sm hover:bg-error hover:text-white transition-colors duration-300" do %>
        <%= icon "trash", library: "heroicons", class: "size-4 inline" %>
        Delete
        <% end %>
        <% end %>
    </div>
</div>

app/views/posts/_reactions.html.erb
<div class="flex gap-2">

    <!-- Reaction Counter -->
    <div class="flex items-center gap-2 px-4 py-2 bg-pink-50 border border-pink-200 rounded-full shadow-sm">
        <span class="text-lg">
            <%= icon "heart", library: "heroicons", variant: "solid", class: "size-6 text-red-700" %>
        </span>
        <span class="font-semibold text-pink-600">
            <%= post.reactions.count %>
        </span>
    </div>

    <% if user_signed_in? %>
    <% reaction = post.reactions.find_by(user: current_user) %>

    <% if reaction %>
    <!-- Unlike Button -->
    <%= link_to post_reaction_path(post, reaction), class: "btn btn-accent rounded-full", data: { turbo_method: :delete } do %>
    <%= icon "heart", library: "heroicons", variant: "solid", class: "size-6 text-red-700" %>
    Liked
    <% end %>

    <% else %>
    <!-- Like Button -->
    <%= link_to post_reactions_path(post), class: "btn btn-outline btn-accent rounded-full", data: { turbo_method: :post, turbo_submits_with: "Liking..." } do %>
    <%= icon "heart", library: "heroicons", class: "size-6" %>
    Like
    <% end %>
    <% end %>
    <% end %>
</div>
</div>

app/views/posts/_user.html.erb
<!-- <li>
    <% if user_signed_in?%>
    <%= "#{current_user.email}, #{current_user.encrypted_password}" %>
    <% end %>
<li>

app/views/posts/edit.html.erb
<div class="w-full max-w-2xl mx-auto shadow-2xl rounded-lg p-12 mt-12">
    <h1 class="text-center text-3xl font-bold mb-8">Edit post</h1>
    <%= render "form", post: @post %>
</div>

app/views/posts/index.html.erb
<div class="min-h-screen p-12 pt-8 lg:px-16">
    <div class="flex justify-between items-center mb-8">
        <div class="flex items-center space-x-4 w-[22%]">
            <h1 class="text-lg md:text-4xl lg:text-2xl font-bold m-4 typewriter">
                BLOG POSTS
            </h1>
        </div>
        <div>
            <% if admin? %>
            <%= link_to new_post_path, class: "btn btn-primary flex items-center gap-2" do %>
            <%= icon "plus", library: "heroicons", class: "size-4 inline" %>
            New post
            <% end %>
            <% end %>
        </div>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
        <%= render partial: "post", collection: @posts %>
    </div>
</div>

app/views/posts/my_post.html.erb
<% if admin? %>
<div class="min-h-screen py-12 px-4">

    <!-- Page Title -->
    <div class="max-w-3xl mx-auto mb-10 text-center">
        <h1 class="text-3xl md:text-4xl font-extrabold mb-2">
            My Posts
        </h1>
        <p class="text-sm">
            Manage and revisit your published content ✍️
        </p>
    </div>

    <div class="max-w-3xl mx-auto">
        <% if @posts.any? %>

        <div class="space-y-4">
            <% @posts.each do |post| %>
            <div class="rounded-xl shadow-lg hover:shadow-2xl transition-all duration-300 p-5 flex justify-between items-center group">

                <!-- Post Info -->
                <div>
                    <%= link_to post.title, post_path(post),
                    class: "text-lg font-semibold group-hover:text-blue-600 transition duration-200" %>

                    <p class="text-sm mt-1 italic">
                        <%= post.created_at.strftime("%B %d, %Y") %>
                    </p>
                </div>

                <!-- Quick Action -->
                <%= link_to "View",
                    post_path(post),
                    class: "btn btn-info btn-sm w-[10%]" %>
            </div>
            <% end %>
        </div>

        <% else %>

        <!-- Empty State -->
        <div class="rounded-xl p-10 text-center shadow-xl">
            <p class="mb-4">
                You haven’t created any posts yet.
            </p>
            <%= link_to "Create Your First Post",
                new_post_path,
                class: "btn btn-primary btn-outline" %>
        </div>

        <% end %>
    </div>
</div>
<% end %>

app/views/posts/new.html.erb
<div class="w-full max-w-2xl mx-auto shadow-xl p-12 mt-12">
    <h1 class="text-center text-3xl font-bold mb-8">New post</h1>
    <%= render "form", post: @post %>
</div>

app/views/posts/show.html.erb
<div class="w-full max-w-2xl mx-auto mt-4 p-8 md:p-12 shadow-2xl rounded-xl animate-fade-in">
    <!-- Post Header -->
    <div class="mb-8 text-center">
        <h1 class="text-3xl md:text-4xl font-extrabold mb-2">
            <%= @post.title %>
        </h1>
        <span class="text-sm italic block">
            Posted by <%= @post.user.username %> (<%= @post.user.email %>)
        </span>
        <span class="text-xs md:block italic mt-1">
            Published on <%= @post.created_at.strftime("%B %d, %Y %H:%M") %>
        </span>
    </div>

    <!-- Post Image -->
    <% if @post.image.attached? %>
    <div class="mb-8">
        <%= image_tag @post.image.variant(resize_to_limit: [1200, 800]), class: "w-full h-75 rounded-lg shadow-md object-cover" %>
    </div>
    <% end %>

    <!-- Post Body -->
    <div class="mb-8 space-y-4 text-lg leading-relaxed">
        <p><%= @post.body %></p>
    </div>

    <!-- Actions -->
    <div class="mb-8 space-x-3 flex inline-flex">
        <%= link_to posts_path, class: "btn btn-outline btn-sm flex items-center gap-2" do %>
        <%= icon "arrow-left", library: "heroicons", variant: "solid", class: "size-4 inline" %>
        Back to posts
        <% end %>
        <% if user_signed_in? && current_user == @post.user %>
        <%= link_to edit_post_path(@post), class: "link link-hover link-info text-sm flex items-center gap-2" do %>
        <%= icon "pencil-square", library: "heroicons", variant: "solid", class: "size-4 inline" %>
        Edit
        <% end %>
        <%= link_to @post, data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this post?" }, class: "link link-hover link-error text-sm flex items-center gap-2" do %>
        <%= icon "trash", library: "heroicons", variant: "solid", class: "size-4 inline" %>
        Delete
        <% end %>
        <% end %>
    </div>

    <!-- Comments Form -->
    <div class="mb-6">
        <%= render "comments/form" %>
    </div>

    <!-- Reactions / Likes -->
    <div>
        <%= render "posts/reactions", post: @post %>
    </div>
</div>